#!/usr/bin/env bash
# tint-create — standalone theme creator (no Claude Code required)
# For the intelligent path, use /tint-create inside Claude Code instead.

set -e

THEMES_DIR="$HOME/.terminal-themes"
mkdir -p "$THEMES_DIR"

echo "tint-create"
echo "==========="
echo ""
echo "Enter 2-6 brand hex colors, space-separated."
echo "First color = background hue. Second = foreground or cursor."
echo ""
echo "Example: #008438 #F6EEE6 #1882FF #FF5C4D"
echo ""
read -r -p "colors: " COLOR_INPUT

# Parse colors into array
colors=()
for c in $COLOR_INPUT; do
  c="${c#\#}"  # strip leading #
  [[ ${#c} -eq 6 ]] && colors+=("$c") || echo "skipping invalid: $c"
done

if [[ ${#colors[@]} -lt 2 ]]; then
  echo "Need at least 2 colors."
  exit 1
fi

# Hex math helpers
hex_r() { printf "%d" "0x${1:0:2}"; }
hex_g() { printf "%d" "0x${1:2:2}"; }
hex_b() { printf "%d" "0x${1:4:2}"; }

darken() {
  local hex="$1" factor="${2:-0.35}"
  local r=$(hex_r "$hex") g=$(hex_g "$hex") b=$(hex_b "$hex")
  r=$(printf "%.0f" "$(echo "$r * $factor" | bc)")
  g=$(printf "%.0f" "$(echo "$g * $factor" | bc)")
  b=$(printf "%.0f" "$(echo "$b * $factor" | bc)")
  printf "%02x%02x%02x" "$r" "$g" "$b"
}

lighten() {
  local hex="$1" factor="${2:-0.3}"
  local r=$(hex_r "$hex") g=$(hex_g "$hex") b=$(hex_b "$hex")
  r=$(printf "%.0f" "$(echo "$r + (255 - $r) * $factor" | bc)")
  g=$(printf "%.0f" "$(echo "$g + (255 - $g) * $factor" | bc)")
  b=$(printf "%.0f" "$(echo "$b + (255 - $b) * $factor" | bc)")
  printf "%02x%02x%02x" "$r" "$g" "$b"
}

# Luminance check (rough)
luminance() {
  local hex="$1"
  local r=$(hex_r "$hex") g=$(hex_g "$hex") b=$(hex_b "$hex")
  echo "($r * 299 + $g * 587 + $b * 114) / 1000" | bc
}

# Build palette
bg=$(darken "${colors[0]}" 0.35)
fg="${colors[1]}"

# Check if fg is light enough against bg
fg_lum=$(luminance "$fg")
if [[ $fg_lum -lt 160 ]]; then
  fg=$(lighten "$fg" 0.5)
fi

cursor="${colors[2]:-$fg}"
sel_bg=$(lighten "$bg" 0.3)

# ANSI slots — fill from brand colors, pad with defaults
ansi=()
for i in $(seq 0 15); do
  idx=$(( (i % ${#colors[@]}) ))
  if [[ $i -lt 8 ]]; then
    ansi+=("${colors[$idx]}")
  else
    ansi+=("$(lighten "${colors[$idx]}" 0.2)")
  fi
done

# Override black/white slots
ansi[0]=$(darken "$bg" 0.7)
ansi[7]=$(lighten "$fg" 0.1)
ansi[8]=$(lighten "$bg" 0.4)
ansi[15]=$(lighten "$fg" 0.2)

# Default name from current directory
default_name="${PWD##*/}"
default_name="${default_name,,}"  # lowercase
theme_name="$default_name"

# Save theme file first
cat > "$THEMES_DIR/$theme_name.sh" << THEME
# $theme_name — generated by tint-create

# Background via OSC 11 (triggers titlebar sync)
printf '\e]11;#${bg}\e\\\\'

# Everything else via OSC 21
printf '\e]21;foreground=#${fg};cursor=#${cursor};cursor_text=#${bg};selection_background=#${sel_bg};selection_foreground=#${ansi[15]};0=#${ansi[0]};1=#${ansi[1]};2=#${ansi[2]};3=#${ansi[3]};4=#${ansi[4]};5=#${ansi[5]};6=#${ansi[6]};7=#${ansi[7]};8=#${ansi[8]};9=#${ansi[9]};10=#${ansi[10]};11=#${ansi[11]};12=#${ansi[12]};13=#${ansi[13]};14=#${ansi[14]};15=#${ansi[15]}\e\\\\'
THEME

echo "Saved to ~/.terminal-themes/$theme_name.sh"
echo ""
echo "Preview it in another terminal:"
echo "  tint $theme_name"
echo ""

read -r -p "Keep as [$theme_name]? Or enter a different name: " new_name
if [[ -n "$new_name" && "$new_name" != "$theme_name" ]]; then
  mv "$THEMES_DIR/$theme_name.sh" "$THEMES_DIR/$new_name.sh"
  sed -i '' "s/^# $theme_name/# $new_name/" "$THEMES_DIR/$new_name.sh"
  echo "Renamed to ~/.terminal-themes/$new_name.sh"
  echo "Use: tint $new_name"
else
  echo "Use: tint $theme_name"
fi
